spring.application.name=jakone-be

server.port=8080

# Environment variables with fallbacks for local running vs. Docker
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bank_dki_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:dev_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:dev_password}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.transaction=TRACE
logging.level.org.springframework.orm.jpa=DEBUG

# Spring Web Error Configuration
spring.web.error.include-message=always
spring.web.error.include-binding-errors=always
spring.web.error.include-stacktrace=always
spring.web.error.include-exception=true